await page.goto("https://developer.apple.com/account/resources/identifiers/list/applicationGroup");
await page.waitForTimeout(9000);
if ((await page.innerText("body")).includes("group.com.mattbusel.baselineledger")) return "exists";
await page.goto("https://developer.apple.com/account/resources/identifiers/applicationGroup/add/");
await page.waitForTimeout(8000);
await page.fill("#description", "Baseline Ledger shared");
await page.fill("#identifier", "group.com.mattbusel.baselineledger");
await page.getByRole("button", { name: "Continue" }).click(); await page.waitForTimeout(4000);
await page.getByRole("button", { name: "Register" }).click(); await page.waitForTimeout(6000);
return (await page.innerText("body")).includes("group.com.mattbusel.baselineledger") ? "created" : "check";
